const int maps[MAX_LEVEL][GRID_Y][GRID_X] = {
       {
        {  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,   END },
        { START, FLOOR, FLOOR,  WALL,  WALL, FLOOR, FLOOR,  WALL, FLOOR, FLOOR },
        { FLOOR,  ROCK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR,  WALL, FLOOR,  WALL },
        { FLOOR, FLOOR, FLOOR,  WALL, FLOOR, FLOOR, FLOOR,  WALL,  HOLE,  WALL },
        {  WALL, FLOOR, FLOOR,  WALL,  HOLE,  WALL,  WALL,  WALL, FLOOR, FLOOR },
        {  WALL,  WALL, FLOOR,  WALL, FLOOR, FLOOR,  WALL,  WALL, FLOOR, FLOOR },
        { FLOOR, FLOOR,  ROCK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR,  HOLE },
        {  WALL, FLOOR, FLOOR, FLOOR,  WALL, FLOOR, FLOOR, FLOOR, FLOOR,  WALL }
       },
       {
        { START, FLOOR, FLOOR, FLOOR,  WALL,  WALL,  ROCK,  WALL,   END,  WALL },
        { FLOOR,  ROCK, FLOOR,  ROCK, FLOOR,  WALL, FLOOR,  WALL, FLOOR,  WALL },
        { FLOOR, FLOOR, FLOOR, FLOOR, FLOOR,  WALL,  WALL, FLOOR, FLOOR,  WALL },
        { FLOOR,  ROCK, FLOOR, FLOOR, FLOOR,  WALL,  WALL,  HOLE,  WALL,  WALL },
        {  WALL,  WALL,  HOLE,  HOLE,  HOLE,  WALL, FLOOR, FLOOR, FLOOR, FLOOR },
        { FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR },
        {  WALL, FLOOR, FLOOR,  WALL, FLOOR, FLOOR,  WALL, FLOOR, FLOOR,  WALL },
        {  WALL,  WALL,  WALL,  WALL, FLOOR, FLOOR,  WALL, FLOOR,  WALL,  WALL }
       },
       {
        { START, FLOOR,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,   END,  WALL },
        { FLOOR, FLOOR,  WALL,  WALL,  WALL,  WALL,  WALL, FLOOR, FLOOR,  WALL },
        {  WALL, FLOOR, FLOOR,  ROCK, FLOOR, FLOOR,  WALL, FLOOR,  HOLE, FLOOR },
        {  WALL, FLOOR,  ROCK, FLOOR,  ROCK,  ROCK,  WALL,  WALL,  HOLE,  WALL },
        {  WALL, FLOOR,  ROCK, FLOOR, FLOOR,  ROCK,  WALL, FLOOR,  HOLE, FLOOR },
        {  WALL, FLOOR, FLOOR,  ROCK,  ROCK,  ROCK,  HOLE, FLOOR, FLOOR, FLOOR },
        {  WALL, FLOOR, FLOOR,  ROCK, FLOOR, FLOOR,  WALL, FLOOR, FLOOR,  WALL },
        {  WALL,  WALL,  WALL, FLOOR, FLOOR, FLOOR,  WALL,  WALL,  HOLE,  WALL }        
       },
       {
        { START, FLOOR,  WALL,  WALL,  WALL, FLOOR,  WALL,  WALL,  WALL,   END },
        { FLOOR,  ROCK, FLOOR,  WALL,  WALL, FLOOR, FLOOR, FLOOR, FLOOR,  HOLE },
        { FLOOR, FLOOR, FLOOR,  WALL,  WALL,  WALL,  ROCK, FLOOR, FLOOR, FLOOR },
        { FLOOR, FLOOR,  WALL,  WALL, FLOOR,  WALL, FLOOR, FLOOR, FLOOR,  WALL },
        { FLOOR, FLOOR,  HOLE,  ROCK, FLOOR, FLOOR, FLOOR,  ROCK,  HOLE,  WALL },
        {  HOLE,  WALL,  WALL,  WALL, FLOOR, FLOOR, FLOOR,  WALL, FLOOR,  WALL },
        { FLOOR, FLOOR, FLOOR,  WALL,  WALL,  WALL,  WALL,  WALL, FLOOR, FLOOR },
        { FLOOR,  ROCK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR }
       },
       {
        {  WALL, FLOOR, FLOOR, FLOOR,  WALL, FLOOR,  ROCK, FLOOR, FLOOR,  WALL },
        {  WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR,  WALL,  WALL },
        { FLOOR, FLOOR,  WALL,  HOLE,  WALL,  WALL, FLOOR,  WALL,  WALL,  WALL },
        { START, FLOOR,  HOLE, FLOOR,  HOLE, FLOOR, FLOOR,  HOLE,   END,  WALL },
        {  WALL, FLOOR,  WALL, FLOOR,  WALL,  WALL,  ROCK,  WALL,  WALL,  WALL },
        {  WALL, FLOOR,  WALL, FLOOR, FLOOR, FLOOR,  ROCK, FLOOR,  WALL,  WALL },
        {  WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR,  ROCK, FLOOR, FLOOR,  WALL },
        {  WALL,  WALL,  WALL,  WALL,  HOLE, FLOOR,  ROCK, FLOOR, FLOOR,  WALL }
       },
       {
        {  WALL,  WALL,  WALL,  WALL, FLOOR, FLOOR,  WALL, FLOOR, FLOOR,  WALL },
        {  WALL,  WALL, FLOOR, FLOOR, FLOOR, FLOOR,  HOLE, FLOOR, FLOOR, FLOOR },
        {  WALL,  WALL, FLOOR,  ROCK, FLOOR,  ROCK,  WALL,  ROCK, FLOOR,  WALL },
        { START, FLOOR, FLOOR,  HOLE,  HOLE,  HOLE,  HOLE,  HOLE,  HOLE,   END },
        {  WALL,  WALL,  WALL,  WALL,  ROCK, FLOOR,  ROCK, FLOOR,  WALL,  WALL },
        {  WALL,  WALL,  WALL, FLOOR, FLOOR, FLOOR,  WALL, FLOOR, FLOOR, FLOOR },
        {  WALL,  WALL,  WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR,  WALL },
        {  WALL,  WALL,  WALL,  WALL,  WALL,  ROCK, FLOOR,  WALL,  WALL,  WALL }
       }
};

void initLevel() {
  for(int i = 0; i < GRID_X; i++) {
    for(int j = 0; j < GRID_Y; j++) {
      pattern[j][i] = maps[currentLevel][j][i];
    }
  }
  initRocks();
  initPlayer();
}